<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DuetHQ.Web.Client\DuetHQ.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\DuetHQ.Infrastructure.Common\DuetHQ.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\Modules\Organization\DuetHQ.Modules.Organization\DuetHQ.Modules.Organization.csproj" />
    <ProjectReference Include="..\Modules\Content\DuetHQ.Modules.Content\DuetHQ.Modules.Content.csproj" />
    <ProjectReference Include="..\Modules\CheckIn\DuetHQ.Modules.CheckIn\DuetHQ.Modules.CheckIn.csproj" />
    <ProjectReference Include="..\Modules\Personal\DuetHQ.Modules.Personal\DuetHQ.Modules.Personal.csproj" />
    <ProjectReference Include="..\Modules\Insights\DuetHQ.Modules.Insights\DuetHQ.Modules.Insights.csproj" />
    <ProjectReference Include="..\Modules\Actions\DuetHQ.Modules.Actions\DuetHQ.Modules.Actions.csproj" />
    <ProjectReference Include="..\Modules\Notifications\DuetHQ.Modules.Notifications\DuetHQ.Modules.Notifications.csproj" />
    <ProjectReference Include="..\Modules\Pilot\DuetHQ.Modules.Pilot\DuetHQ.Modules.Pilot.csproj" />
  </ItemGroup>

</Project>
