<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\DuetHQ.SharedKernel\DuetHQ.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DuetHQ.Application.Abstractions\DuetHQ.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DuetHQ.Infrastructure.Common\DuetHQ.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\DuetHQ.Modules.Content.Contracts\DuetHQ.Modules.Content.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
</Project>
