<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Hamdel.SharedKernel\Hamdel.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Hamdel.Application.Abstractions\Hamdel.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Hamdel.Infrastructure.Common\Hamdel.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\Hamdel.Modules.Organization.Contracts\Hamdel.Modules.Organization.Contracts.csproj" />
  </ItemGroup>
</Project>
