<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\DuetHQ.SharedKernel\DuetHQ.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DuetHQ.Application.Abstractions\DuetHQ.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\DuetHQ.Infrastructure.Common\DuetHQ.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\DuetHQ.Modules.CheckIn.Contracts\DuetHQ.Modules.CheckIn.Contracts.csproj" />
    <ProjectReference Include="..\..\Organization\DuetHQ.Modules.Organization.Contracts\DuetHQ.Modules.Organization.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\DuetHQ.Modules.Content.Contracts\DuetHQ.Modules.Content.Contracts.csproj" />
    <ProjectReference Include="..\..\Personal\DuetHQ.Modules.Personal.Contracts\DuetHQ.Modules.Personal.Contracts.csproj" />
    <ProjectReference Include="..\..\Insights\DuetHQ.Modules.Insights.Contracts\DuetHQ.Modules.Insights.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
</Project>
