<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Hamdel.SharedKernel\Hamdel.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Hamdel.Application.Abstractions\Hamdel.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Hamdel.Infrastructure.Common\Hamdel.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\Hamdel.Modules.Insights.Contracts\Hamdel.Modules.Insights.Contracts.csproj" />
    <ProjectReference Include="..\..\Organization\Hamdel.Modules.Organization.Contracts\Hamdel.Modules.Organization.Contracts.csproj" />
    <ProjectReference Include="..\..\Content\Hamdel.Modules.Content.Contracts\Hamdel.Modules.Content.Contracts.csproj" />
    <ProjectReference Include="..\..\CheckIn\Hamdel.Modules.CheckIn.Contracts\Hamdel.Modules.CheckIn.Contracts.csproj" />
  </ItemGroup>
</Project>
